services:
  - type: web
    name: skyeats-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/skyeats-backend-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: PORT
        value: 8080