server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://namansethia5:iXa6cfFBLMP1Hh7g@cluster0.5jtifc9.mongodb.net/?appName=Cluster0}
      database: skyeats

firebase:
  project-id: ${FIREBASE_PROJECT_ID:akasa-9c735}
  credentials-path: ${GOOGLE_APPLICATION_CREDENTIALS:}
  credentials-json: ${GOOGLE_APPLICATION_CREDENTIALS_JSON:}

logging:
  level:
    com.skyeats: DEBUG
    org.springframework.security: DEBUG